#!/bin/bash

# Description ##################################################################
# Helper functions and global variables

USER_DIR=/home/xxxxxxxxxx
SERVER_DIR=/home/xxxxxxxxxx
MOD_DIR=/home/xxxxxxxxxx/insurgency_server
SERVER_LOG_DIR=$SERVER_DIR/sandstorm/Insurgency/Saved/Logs/Insurgency.log
ADMIN_DIR=$SERVER_DIR/sandstorm/Insurgency/Config/Server/Admins.txt
PRIORITY_DIR=$MOD_DIR/config/priorityPlayers.txt

RCON_PWD=xxxxxxxxxx
RCON_IP=xxxxxxxxxx
RCON_PORT=xxxxxxxxxx
STEAM_API_KEY=xxxxxxxxxx

function rconn() {
  rcon -H $RCON_IP -p $RCON_PORT -P $RCON_PWD $1
}

function getNumPlayers() {
  numPlayers=$( python $USER_DIR/python-valve/tests/getSandstormServerInfo.py )
  error=$( echo "$numPlayers" | grep -c Error ) # Expected result: "1"

  if [ $error -gt 0 ]; then
    echo "Error: Could not get number of players from API service."
  else
    echo $numPlayers
  fi
}

function getSteamNameFromId() {
  steamId=$1
  steamName=$( python $USER_DIR/insurgency_server/services/convertSteamIdToName.py $steamId )
  error=$( echo "$steamName" | grep -c Error ) # Expected result: "1"

  if [ $error -gt 0 ]; then
    echo "Someone"
  else
    echo $steamName
  fi
}

function getPlayerList() {
  rawPlayerList=$( rconn "listplayers" )
  echo $rawPlayerList | grep -oP "765\d*"
}

function isAdmin() {
  steamId=$1
  if grep -Fxq "$steamId" "$ADMIN_DIR"; then
    return 0 # true
  else
    return 1 # false
  fi
}

function isPriorityPlayer() {
  steamId=$1
  if grep -Fxq "$steamId" "$PRIORITY_DIR"; then
    return 0 # true
  else
    return 1 # false
  fi
}