#!/bin/bash

teamsay="[2019.10.08-00.25.36:669][406]LogChat: Display: James(765123413412341234) Global Chat: !botcount 12 James(765123413412341236) !botcount 14"
# teamsay="[2019.10.08-00.25.43:486][813]LogChat: Display: James(765123413412341234) Team 0 Chat: !hi 1287y !hi 987 James(765123413412341236)"
# LINE=$allsay

chatMessage="LogChat: Display: "
steamId=$( echo "$teamsay" | grep -shoP "\((.*?765.*?)\)" | head -n1 )
# steamId3=$steamId

steamId2=${steamId:1:-1}

echo "$steamId2"
adminId="765123413412341234"

if [[ "$adminId" == "$steamId2" ]]; then
	echo "You are admin."
else
	echo "Intruder alert."
fi

requestCommand=$( echo $teamsay | grep -oP "Chat:\s\!(.*?)\s\d\d" )
# requestCommand=$( echo $teamsay | grep -oP "!(.*?)" )
echo $requestCommand
# echo "$adminId...2"

# if [[ $teamsay =~ $chatMessage ]]; then
#   if [[ $steamId2 == $adminId ]]; then
#     echo "$requestCommand..."
#   else
#     echo "Nice try."
#   fi
# fi
