#!/bin/bash

# Purpose ######################################################################
# Insurgency: Sandstorm checkpoint co-op mode relies on capturing objectives
# A, B, etc on each map. The capture timer game variable can be adjusted in
# real-time via an rcon message. Since the game logs certain events in a log
# file, certain events are captured to start a timer to prevent players from
# capturing a point too fast--a playstyle that can cause teammates, who aren't
# ready, to die from newly spawned enemies after an early capture. Locking the
# objective helps the slower, tactical gameplay, server admins, and fosters the 
# overall identity of the server, which seems to have an effect on attracting 
# tactical players.

# $SERVER_LOG_DIR, rconn($1), getNumPlayers
source ../commonUtils

# Locks the current objective by inceasing the timer and begins the countdown
# as close to the timer at the bottom of the screen.
function normalCaptureOnLowPlayerCount() {
  numPlayers=$( getNumPlayers )
  if [ $numPlayers -le 3 ]; then
    $MOD_DIR/helper_functions/killTimer
    rconn "gamemodeproperty ObjectiveCaptureTime 30"
    echo -e "\n$numPlayers players detected. Timer killed. Normal checkpoint timer."
  fi
}

function startTimer() {
  extendTimer=$1
  $extendtimer
  $MOD_DIR/helper_functions/countdown &
}

function handleObjectiveLock() {
  objType=$1
  $MOD_DIR/helper_functions/killTimer

  extendTimer=""
  if [[ $objType == "firstObj" ]]; then
    extendTimer=$( sleep 3 ) # Match sleep with PreRoundTimer in Game.ini
  fi

  startTimer $extendtimer
  normalCaptureOnLowPlayerCount
}

# If timer was never stopped, stop it before this script begins.
$MOD_DIR/helper_functions/killTimer

tail -n 0 -F $SERVER_LOG_DIR 2>&1 | \

while read -r LINE; do
  # Regex Identifiers
  onRoundStart="Match State Changed from (GameStarting|RoundActive|PostRound) to PreRound"
  onObjectiveCapture="Advancing spawns for faction 255 to obj [1-9]: 1 zones enabled"

  if [[ ($LINE =~ $onRoundStart) || ($LINE =~ $onObjectiveCapture) ]]; then
    objType=""
    if [[ $LINE =~ $onRoundStart ]]; then
      objType="firstObj"
    fi

    handleObjectiveLock $objType
  fi

done
